add dependency react-pdf, create pdf-display component
BloomTech-Labs/story-squad-fe-archived pull request #25
Opened 2020-01-30 22:48 UTC by EricBanker12

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-01-30 22:56 UTC, EricBanker12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Child] - React-PDF for text highlighting](https://trello.com/c/7TMXeIIY/47-child-react-pdf-for-text-highlighting)

2020-01-30 23:54 UTC, wSedlacek requested changes
Let's try to get `react-pdf` out of the main bundle.
If necessary dynamically load all of `pdf-display`

2020-01-30 23:54 UTC, wSedlacek commented on package.json
>          "@types/pdfjs-dist": "^2.1.3",
If you are remove `pdfjs-dist` then you need to remove the types too

2020-01-30 23:54 UTC, wSedlacek commented on src/app/components/pdf-display/pdf-display/pdf-display.component.tsx
> +import { Document, Page } from 'react-pdf';
This is going to have a large bundle size.
Please refer to https://reactjs.org/docs/code-splitting.html

2020-02-03 14:36 UTC, ghost reviewed
replace PDF reader.

2020-02-03 19:01 UTC, wSedlacek approved these changes
![Screen Shot 2020-02-03 at 12 58 54](https://user-images.githubusercontent.com/8206108/73682035-2eeb7900-4685-11ea-9298-dcee7ae7906f.png)

The size looks much better if this works in staging then it is good to merge

2020-02-04 18:33 UTC, merged