add up to 5 image submissions for story
BloomTech-Labs/story-squad-fe-archived pull request #27
Opened 2020-02-01 02:12 UTC by EricBanker12

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-02-03 16:57 UTC, EricBanker12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Child] - Upload multiple images](https://trello.com/c/LVfc6AnV/52-child-upload-multiple-images)

2020-02-03 16:57 UTC, EricBanker12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Child] - Upload multiple images](https://trello.com/c/LVfc6AnV/52-child-upload-multiple-images)

2020-02-03 20:41 UTC, wSedlacek requested changes

2020-02-03 20:41 UTC, wSedlacek commented on src/index.tsx
> +require('polyfill-object.fromentries');
Can you make a `polyfill.ts` and use the `import 'polyfill-object.fromentrie'` syntax?

2020-02-03 20:41 UTC, wSedlacek commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +    }, [state]);
What is this cascading for?

2020-02-03 20:41 UTC, wSedlacek commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +};
Why is initial state outside of the body of the component?

2020-02-03 20:41 UTC, wSedlacek commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +                        )}
Could we map over these to reduce the length of the JSX?

2020-02-03 20:54 UTC, Forrestdarabian approved these changes
Overall very well-structured and clean. Left a couple comments on things to maybe think about/include, but overall great job

2020-02-03 20:54 UTC, Forrestdarabian commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +};
I would include initial state inside of the body unless you had a specific reasoning for it?

2020-02-03 20:54 UTC, Forrestdarabian commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +    }, [state]);
Looking good, well organized

2020-02-03 20:54 UTC, Forrestdarabian commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +                        )}
Agree with William on the mapping

2020-02-03 21:16 UTC, EricBanker12 commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +    }, [state]);
This removes other pages when you remove the first. Otherwise you can submit page 2 without page 1.

2020-02-03 22:37 UTC, EricBanker12 commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +};
If initState is inside the body, it is redeclared every render, triggering a useEffect with initState dependency to trigger in an infinite loop.

2020-02-03 22:47 UTC, EricBanker12 commented on src/app/components/child-dashboard/creative-content-submission/form/form.component.tsx
> +                        )}
Implemented

2020-02-03 22:47 UTC, EricBanker12 commented on src/index.tsx
> +require('polyfill-object.fromentries');
Implemented

2020-02-04 21:29 UTC, wSedlacek approved these changes
Looks good, has some room for improvement that that can be addressed in future updates

2020-02-04 21:29 UTC, merged