Create account
BloomTech-Labs/story-squad-fe-archived pull request #3
Opened 2019-12-19 20:12 UTC by wSedlacek

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2019-12-20 16:21 UTC, wSedlacek commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Parent] - Create an account](https://trello.com/c/3zKsookg/19-parent-create-an-account)

2019-12-20 23:13 UTC, ghost reviewed
readuced budle size. added react-app-rewired

2019-12-20 23:15 UTC, ghost reviewed
sign up formatting with material ui and form setting up.

2019-12-20 23:17 UTC, ghost reviewed
setting up of sign up and connecting with Back end.

2019-12-20 23:19 UTC, ghost reviewed
fixed sign in page to make it functional with on change. and added types as email and password.

2020-01-07 02:24 UTC, wSedlacek commented
If this could be reviewed that would be awesome.
Let me know if there are any areas that you would like to see comments.

2020-01-07 17:06 UTC, EricBanker12 requested changes
Signup renders, but submission is using wrong base url locally. More comments would be appreciated for the custom hooks.

2020-01-07 17:06 UTC, EricBanker12 commented on src/app/hooks/form/form.hook.ts
> +    };
This highly nested function is a bit confusing, and a comment would be helpful.

2020-01-07 17:06 UTC, EricBanker12 commented on src/app/components/sign-up/sign-up.component.tsx
> +                    label='Username'
Username is an unintuitive label for email.

2020-01-07 17:06 UTC, EricBanker12 commented on src/app/util/requestFactory.ts
> +        baseURL: process.env.REACT_APP_ENDPOINT,
Undefined. Locally, requests are defaulting to localhost:3000.

2020-01-07 19:01 UTC, EricBanker12 approved these changes
Everything appears to be working, but there is a minor memory leak I believe is caused by form.hook or api.hook on login due to triggering a state change in a hook called by an unmounted component after redirecting to dashboard.

2020-01-07 21:36 UTC, merged