Privacy policy
BloomTech-Labs/story-squad-fe-archived pull request #4
Opened 2019-12-19 21:21 UTC by BNMoyers

# Description
Privacy Policy copy implemented as a simple react component, for display on an as-yet-to-be-determined page.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2019-12-20 22:55 UTC, ghost reviewed
added graig's comments

2019-12-20 22:57 UTC, ghost reviewed
start of writing down privacy policy.

2019-12-20 22:57 UTC, ghost reviewed
Well formatted privacy policy.

2020-01-06 23:00 UTC, EricBanker12 requested changes
There are a couple minor typos that got through and some very basic testing (does it render) testing should be added.

2020-01-06 23:00 UTC, EricBanker12 commented on src/app/components/policies/privacy-policy.component.tsx
> +const PrivacyPolicy: <React className="FC"></React> = () => {
Autocomplete messed up this line. Should be:
```
const PrivacyPolicy: React.FC = () => {
```

2020-01-06 23:00 UTC, EricBanker12 commented on src/app/pages/tos.page.tsx
> +export { PrivacyPage };
Should be `export { ToSPage };`

2020-01-06 23:25 UTC, EricBanker12 approved these changes
Some of the component and page naming could be better, but it's good enough for my approval.

2020-01-07 02:23 UTC, wSedlacek approved these changes
There is some cleanup to do with white spaces and what not but this can be cleaned as we go.
Good work Britney!

2020-01-07 16:31 UTC, merged